version: '3'

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: ays-server
    volumes:
      - .:/usr/local/api
    container_name: nest-api